[package]
name = "if97"
crate-type   = ["rlib", "cdylib"]
version = "0.4.0"
edition = "2021"
authors = ["Cheng Maohua <cmh@seu.edu.cn>"]
description = "The high-speed IAPWS-IF97 package"
readme = "README.md"
homepage = "https://github.com/thermalogic/"
repository = "https://github.com/thermalogic/IF97/"
license = "MIT"
keywords = ["IF97", "IAPWS-IF97"]
categories = ["science"]

[dev-dependencies]
assert_approx_eq = "1.1.0"