[package]
name = "if97"
version = "0.1.0"
edition = "2021"
authors = ["Cheng Maohua <cmh@seu.edu.cn>"]
description = "The high-speed IAPWS-IF97 package"
readme = "README.md"
homepage = "https://github.com/thermalogic/"
repository = "https://github.com/thermalogic/IF97/"
license = "MIT"
keywords = ["IF97", "IAPWS-IF97"]

[dependencies]
assert_approx_eq = "1.1.0"
