name: macos

on:
  push:
    branches: [ "seuif97" ]
  pull_request:
    branches: [ "seuif97" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3
    - name: Build lib
      run: cargo build -r --target x86_64-apple-darwin --features cdecl
   