name: macos

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: macos-latests

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build -r --target x86_64-apple-darwin --features cdecl
   